### ISSUE TITLE
Icloud 3 verification code

### ISSUE THREAD

**Issue by snhnic** [gcobb321/icloud3_v3_docs#4]
I got stuck. I clicked away the code on my iphone after updating home assistant, did not realize it had something to do with icloud3. N oway of resending the code?

**Comment by snhnic** [comment]
I managed to get into configuration by devices so was there I could resend code. But on the integration part it just sticks.

**Comment by gcobb321** [comment]
iCloud3 Configuration Wizard > Enter/ Request Verification Code screen. Then select request the verification code and submit. The iCloud password cookie files will be reset and a new code will be requested. Then enter the code on the same screen (Enter Verification Code should now be selected)  and submit it.

**Comment by snhnic** [comment]
Yes I know, but the problem was in the integration screen. No option to go to the configuration wizard. Just the stupid 6 digit code. When in devices it was possible to get to the configuration wizard.

**Comment by gcobb321** [comment]
HA guys made it confusing on 2023.6 update. See[ here](https://gcobb321.github.io/icloud3_v3/#/chapters/3.0-config-parms)
